use crate::gen_enum::enum_encoding;

enum_encoding!(
    (doc "https://www.iana.org/assignments/address-family-numbers/address-family-numbers.xhtml#address-family-numbers-2"),
    AddressFamily,
    u16,
    (
        (Ipv4,                               1),
        (Ipv6,                               2),
        (NSAP,                               3),
        (HDLC,                               4),
        (BBN1822,                            5),
        (IEEE802,                            6),
        (E163,                               7),
        (E164,                               8),
        (F69,                                9),
        (X121,                               10),
        (IPX,                                11),
        (Appletalk,                          12),
        (DecnetIV,                           13),
        (BanyanVines,                        14),
        (E164WithNSAPFormatSubaddress,       15),
        (DNS,                                16),
        (DistinguishedName,                  17),
        (ASNumber,                           18),
        (XTPOverIpv4,                        19),
        (XTPOverIpv6,                        20),
        (XTPNativeModeXTP,                   21),
        (FibreChannelWorldWidePortName,      22),
        (FibreChannelWorldWideNodeName,      23),
        (GWID,                               24),
        (AFIForL2VPNInformation,             25),
        (MplsTpSectionEndpointIdentifier,    26),
        (MplsTpLspEndpointIdentifier,        27),
        (MplsTpPseudowireEndpointIdentifier, 28),
        (MTIpv4,                             29),
        (MTIpv6,                             30),
        (BGP_SFC,                            31),
        
        (EIGRPCommonServiceFamily,    16384),
        (EIGRPIpv4ServiceFamily,      16385),
        (EIGRPIpv6ServiceFamily,      16386),
        (LISPCanonicalAddressFormat,  16387),
        (BGP_LS,                      16388),
        (MAC48Bit,                    16389),
        (MAC64Bit,                    16390),
        (OUI,                         16391),
        (MAC24,                       16392),
        (MAC40,                       16393),
        (IPv6_64,                     16394),
        (RBridgePortID,               16395),
        (TRILLNickname,               16396),
        (UniversallyUniqueIdentifier, 16397),
        (RoutingPolicyAFI,            16398),
        (MPLSNamespaces,              16399),
    )
);
