pub mod a;
pub mod a6;
pub mod aaaa;
pub mod afsdb;
pub mod amtrelay;
pub mod any;
pub mod apl;
// pub mod ATMA;
// pub mod AVC;
pub mod axfr;
pub mod caa;
// pub mod CDNSKEY;
// pub mod CDS;
pub mod cert;
pub mod cname;
// pub mod CSYNC;
// pub mod DHCID;
// pub mod DLV;
pub mod dname;
pub mod dnskey;
// pub mod DOA;
// pub mod DS;
// pub mod EID;
// pub mod EUI48;
// pub mod EUI64;
// pub mod GID;
// pub mod GPOS;
pub mod hinfo;
// pub mod HIP;
// pub mod HTTPS;
// pub mod IPSECKEY;
// pub mod ISDN;
// pub mod IXFR;
// pub mod KEY;
// pub mod KX;
// pub mod L32;
// pub mod L64;
// pub mod LOC;
// pub mod LP;
pub mod maila;
pub mod mailb;
pub mod mb;
pub mod md;
pub mod mf;
pub mod mg;
pub mod minfo;
pub mod mr;
pub mod mx;
// pub mod NAPTR;
// pub mod NID;
// pub mod NIMLOC;
// pub mod NINFO;
pub mod ns;
// pub mod NSAP_PTR;
// pub mod NSAP;
pub mod nsec;
// pub mod NSEC3;
// pub mod NSEC3PARAM;
pub mod null;
// pub mod NXT;
// pub mod OPENPGPKEY;
// pub mod OPT;
pub mod ptr;
// pub mod PX;
// pub mod RKEY;
// pub mod RP;
pub mod rrsig;
// pub mod RT;
// pub mod SIG;
// pub mod SINK;
// pub mod SMIMEA;
pub mod soa;
// pub mod SPF;
pub mod srv;
// pub mod SSHFP;
// pub mod SVCB;
// pub mod TA;
// pub mod TALINK;
// pub mod TKEY;
pub mod tlsa;
pub mod tsig;
pub mod txt;
// pub mod UID;
// pub mod UINFO;
// pub mod UNSPEC;
// pub mod URI;
pub mod wks;
// pub mod X25;
// pub mod ZONEMD;

// pub mod Unknown;
